### ISSUE TITLE
MIDI Tracks have different start points

### ISSUE THREAD

**Issue by alana314** [jdstmporter/midifiles#1]
Thanks for this! It's been helpful for writing music for a musical sculpture I've been working on (https://www.instagram.com/p/CRjiXCpp6vc/ ).
I noticed when exporting from Logic Pro that each track will have an arbitrary start event tick. For instance, in one track I'm working on, the start events are 16899, 17227, 213, and 1085, and they should all be nearly the same. When I'm using the library I have to subtract the difference between the start times to sync them up again. It could be Logic's output, but when I re-import the MIDI files to logic they're all in sync.

**Comment by jdstmporter** [comment]
Thank you, it’s good to know that my tools are being used to do creative things.

What you’re describing sounds very, very strange.  I will have a look in some Logix Pro files and see what happens.  However, I seem to recall something in the standard that says that the starting point for the tick is arbitrary, as it’s the difference between subsequent values that matters.  It’s possible, if sad, that Apple just decided to be very literal about this.  In that case, a work-around is easy enough to do.  I’ll let you know soonest.

Julian

From: alana314 ***@***.***>
Date: Thursday, 29 July 2021 at 23:06
To: jdstmporter/midifiles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jdstmporter/midifiles] MIDI Tracks have different start points (#1)

Thanks for this! It's been helpful for writing music for a musical sculpture I've been working on (https://www.instagram.com/p/CRjiXCpp6vc/ ).
I noticed when exporting from Logic Pro that each track will have an arbitrary start event tick. For instance, in one track I'm working on, the start events are 16899, 17227, 213, and 1085, and they should all be nearly the same. When I'm using the library I have to subtract the difference between the start times to sync them up again. It could be Logic's output, but when I re-import the MIDI files to logic they're all in sync.

**Comment by alana314** [comment]
Ok thanks for your quick reply! Here is a screenshot of a MIDI file event list and the sample output of:

```
c=MIDIFile(file)
    c.parse()
    for idx, track in enumerate(c):
        track.parse()
        print(str(track))
```
[output.txt](https://github.com/jdstmporter/midifiles/files/6904401/output.txt)
<img width="436" alt="Screen Shot 2021-07-29 at 5 42 29 PM" src="https://user-images.githubusercontent.com/1194589/127582903-7f81f918-2593-40a6-882d-ab387fbc2db7.png">

I also noticed some strange note off events, like output.txt has `MIDI@26347 NOTE_OFF[9] D10 OFF velocity := 128` which I don't believe is in the midi file. I'd attach the MIDI file but it won't let me here.
Thanks!

**Comment by jdstmporter** [comment]
At this point, I can't really do much, other than say I thunk this is fixed, but I'm not sure.  If you still have problems, please let me know.
