### ISSUE TITLE
converting " 'quarter note' in microseconds" on meta event "Set Tempo" to BPM

### ISSUE THREAD

**Issue by omittedSounds** [jdstmporter/midifiles#3]
since "Set Tempo" meta event is defined as the length of a 'quarter note' in microseconds,
code for converting BPM could be the followings.

meta.py
            #return OrderedDict(tempo = Event.build(_bytes[:3])*120/500000)
            return OrderedDict(tempo = 60000000 / Event.build(_bytes[:3]))

if you don't mind, I would like to create a pull request for this.

**Comment by jdstmporter** [comment]
I have just got round to doing something about this.  Happy with your pull request, but I need to check tempo calculations more carefully, as there are other issues.

**Comment by jdstmporter** [comment]
I've actually decided to go with the following:

 microsecondsPerCrotchet=Event.build(_bytes[:3])
 secondsPerCrotchet=microsecondsPerCrotchet/1000000
 crotchetsPerMinute=60000000/microsecondsPerCrotchet
 return OrderedDict(tempo = secondsPerCrotchet, bpm = crotchetsPerMinute)
 
 This retains your version and a corrected version of my duration-based measure.  To clarify, I have renamed yours as bpm, as that, after all, is what it is.

**Comment by jdstmporter** [comment]
fixed, I think.

**Comment by omittedSounds** [comment]
Thank you very much.
We hope that the maintenance will be continued.

**Comment by jdstmporter** [comment]
After my brief period of not responding, so so I,.  Thank you.
